# Generated by Django 5.1.dev20240304192623 on 2024-04-14 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bandas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'Nome',
                'verbose_name_plural': 'Nomes',
            },
        ),
        migrations.CreateModel(
            name='Albuns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, verbose_name='titulo')),
                ('data', models.DateField(verbose_name='data')),
                ('Banda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='disco.bandas')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albuns',
            },
        ),
        migrations.CreateModel(
            name='Musicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, verbose_name='titulo')),
                ('segundos', models.IntegerField(verbose_name='segundos')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='disco.albuns')),
            ],
            options={
                'verbose_name': 'Musica',
                'verbose_name_plural': 'Musicas',
            },
        ),
    ]
