# Generated by Django 5.1.dev20240304192623 on 2024-04-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disco', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bandas',
            options={'verbose_name': 'Banda', 'verbose_name_plural': 'Bandas'},
        ),
        migrations.RenameField(
            model_name='bandas',
            old_name='nome',
            new_name='banda',
        ),
        migrations.AlterField(
            model_name='bandas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
